=== camenduru/stable-diffusion-3.5-large-tost/schema_turbo.json
{
  "$schema": "http://json-schema.org/draft-04/hyper-schema#",
  "type": "object",
  "properties": {
    "readme": {
      "type": "string",
      "title": "Stable Diffusion 3.5",
      "author": "Stability-AI",
      "page": "https://stability.ai/news/introducing-stable-diffusion-3-5",
      "code": "https://github.com/Stability-AI/sd3.5",
      "api": "https://github.com/camenduru/tost-api-examples/blob/main/v1/stable-diffusion-3.5-large.ipynb",
      "tags": [
        "Text to Image"
      ],
      "widget": "readme"
    },
    "positive_prompt": {
      "type": "string",
      "description": "Prompt",
      "widget": "textarea"
    },
    "negative_prompt": {
      "type": "string",
      "description": "Prompt",
      "widget": "textarea"
    },
    "seed": {
      "type": "integer",
      "description": "Seed (if 0 random)"
    },
    "steps": {
      "type": "integer",
      "widget": "select",
      "description": "Steps",
      "oneOf": [
        {
          "description": "4",
          "enum": [
            4
          ]
        },
        {
          "description": "8",
          "enum": [
            8
          ]
        }
      ],
      "default": 20
    },
    "cfg": {
      "type": "number",
      "description": "CFG"
    },
    "sampler_name": {
      "type": "string",
      "widget": "select",
      "description": "Sampler Name",
      "oneOf": [
        {
          "description": "euler",
          "enum": [
            "euler"
          ]
        },
        {
          "description": "heun",
          "enum": [
            "heun"
          ]
        },
        {
          "description": "heunpp2",
          "enum": [
            "heunpp2"
          ]
        },
        {
          "description": "dpm_2",
          "enum": [
            "dpm_2"
          ]
        },
        {
          "description": "lms",
          "enum": [
            "lms"
          ]
        },
        {
          "description": "dpmpp_2m",
          "enum": [
            "dpmpp_2m"
          ]
        },
        {
          "description": "ipndm",
          "enum": [
            "ipndm"
          ]
        },
        {
          "description": "deis",
          "enum": [
            "deis"
          ]
        },
        {
          "description": "ddim",
          "enum": [
            "ddim"
          ]
        },
        {
          "description": "uni_pc",
          "enum": [
            "uni_pc"
          ]
        },
        {
          "description": "uni_pc_bh2",
          "enum": [
            "uni_pc_bh2"
          ]
        }
      ],
      "default": "euler"
    },
    "scheduler": {
      "type": "string",
      "widget": "select",
      "description": "Scheduler",
      "oneOf": [
        {
          "description": "normal",
          "enum": [
            "normal"
          ]
        },
        {
          "description": "sgm_uniform",
          "enum": [
            "sgm_uniform"
          ]
        },
        {
          "description": "simple",
          "enum": [
            "simple"
          ]
        },
        {
          "description": "ddim_uniform",
          "enum": [
            "ddim_uniform"
          ]
        }
      ],
      "default": "simple"
    },
    "width": {
      "type": "integer",
      "description": "Width"
    },
    "height": {
      "type": "integer",
      "description": "Height"
    },
    "example": {
      "type": "string",
      "image1": "https://i.ibb.co/xGMW4B1/Comfy-UI-01545.png",
      "image2": "https://i.ibb.co/k5J9p3Y/Comfy-UI-01529.png",
      "image3": "https://i.ibb.co/gm08LT4/Comfy-UI-01541.png",
      "image4": "https://i.ibb.co/qmN8m5y/Comfy-UI-01543.png",
      "widget": "example"
    }
  },
  "buttons": [
    {
      "id": "enter",
      "label": "ðŸ¥ª Enter"
    }
  ]
}

=== camenduru/stable-diffusion-3.5-large-tost/model_turbo.json
{
    "positive_prompt": "a bottle with a rainbow galaxy inside it on top of a wooden table on a snowy mountain top with the ocean and clouds in the background with a shot glass beside containing darkness beside a snow sculpture in the shape of a fox",
    "negative_prompt": "blurry",
    "seed": 0,
    "steps": 4,
    "cfg": 1.2,
    "sampler_name": "euler",
    "scheduler": "sgm_uniform",
    "width": 1024,
    "height": 1024
}
